"""cards table

Revision ID: 73776afc7dd7
Revises: f5ac8db2e59b
Create Date: 2022-03-24 12:40:20.884997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73776afc7dd7'
down_revision = 'f5ac8db2e59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_word'), 'card', ['word'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_word'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
